### YamlMime:ManagedReference
items:
- uid: OpenTK.Core.Platform.ContextValueSelector
  commentId: T:OpenTK.Core.Platform.ContextValueSelector
  id: ContextValueSelector
  parent: OpenTK.Core.Platform
  children: []
  langs:
  - csharp
  - vb
  name: ContextValueSelector
  nameWithType: ContextValueSelector
  fullName: OpenTK.Core.Platform.ContextValueSelector
  type: Delegate
  source:
    remote:
      path: src/OpenTK.Core/Platform/ContextSettings.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: ContextValueSelector
    path: opentk/src/OpenTK.Core/Platform/ContextSettings.cs
    startLine: 15
  assemblies:
  - OpenTK.Core
  namespace: OpenTK.Core.Platform
  summary: Delegate used to select appropriate context values to use.
  example: []
  syntax:
    content: public delegate int ContextValueSelector(IReadOnlyList<ContextValues> options, ContextValues requested, ILogger? logger)
    parameters:
    - id: options
      type: System.Collections.Generic.IReadOnlyList{OpenTK.Core.Platform.ContextValues}
      description: A list of possible context values.
    - id: requested
      type: OpenTK.Core.Platform.ContextValues
      description: The user requested context values.
    - id: logger
      type: OpenTK.Core.Utility.ILogger
      description: A logger to use for logging.
    return:
      type: System.Int32
      description: The index of the context value to use.
    content.vb: Public Delegate Function ContextValueSelector(options As IReadOnlyList(Of ContextValues), requested As ContextValues, logger As ILogger) As Integer
references:
- uid: OpenTK.Core.Platform
  commentId: N:OpenTK.Core.Platform
  href: OpenTK.html
  name: OpenTK.Core.Platform
  nameWithType: OpenTK.Core.Platform
  fullName: OpenTK.Core.Platform
  spec.csharp:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Core
    name: Core
    href: OpenTK.Core.html
  - name: .
  - uid: OpenTK.Core.Platform
    name: Platform
    href: OpenTK.Core.Platform.html
  spec.vb:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Core
    name: Core
    href: OpenTK.Core.html
  - name: .
  - uid: OpenTK.Core.Platform
    name: Platform
    href: OpenTK.Core.Platform.html
- uid: System.Collections.Generic.IReadOnlyList{OpenTK.Core.Platform.ContextValues}
  commentId: T:System.Collections.Generic.IReadOnlyList{OpenTK.Core.Platform.ContextValues}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<ContextValues>
  nameWithType: IReadOnlyList<ContextValues>
  fullName: System.Collections.Generic.IReadOnlyList<OpenTK.Core.Platform.ContextValues>
  nameWithType.vb: IReadOnlyList(Of ContextValues)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of OpenTK.Core.Platform.ContextValues)
  name.vb: IReadOnlyList(Of ContextValues)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: OpenTK.Core.Platform.ContextValues
    name: ContextValues
    href: OpenTK.Core.Platform.ContextValues.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: OpenTK.Core.Platform.ContextValues
    name: ContextValues
    href: OpenTK.Core.Platform.ContextValues.html
  - name: )
- uid: OpenTK.Core.Platform.ContextValues
  commentId: T:OpenTK.Core.Platform.ContextValues
  parent: OpenTK.Core.Platform
  href: OpenTK.Core.Platform.ContextValues.html
  name: ContextValues
  nameWithType: ContextValues
  fullName: OpenTK.Core.Platform.ContextValues
- uid: OpenTK.Core.Utility.ILogger
  commentId: T:OpenTK.Core.Utility.ILogger
  parent: OpenTK.Core.Utility
  href: OpenTK.Core.Utility.ILogger.html
  name: ILogger
  nameWithType: ILogger
  fullName: OpenTK.Core.Utility.ILogger
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: OpenTK.Core.Utility
  commentId: N:OpenTK.Core.Utility
  href: OpenTK.html
  name: OpenTK.Core.Utility
  nameWithType: OpenTK.Core.Utility
  fullName: OpenTK.Core.Utility
  spec.csharp:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Core
    name: Core
    href: OpenTK.Core.html
  - name: .
  - uid: OpenTK.Core.Utility
    name: Utility
    href: OpenTK.Core.Utility.html
  spec.vb:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Core
    name: Core
    href: OpenTK.Core.html
  - name: .
  - uid: OpenTK.Core.Utility
    name: Utility
    href: OpenTK.Core.Utility.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
